---
- name: install hackazon server 
  remote_user: niftyshorts
  hosts: 10.1.20.102
  become: yes
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  tasks:
    - name: install curl
      apt:
        name: curl
        state: present
        update_cache: yes
       
    - name: Add GPG key for official Docker repository
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: Add add-apt-repository command
      apt:
        name: software-properties-common
        state: present

    - name: Add Docker repository to APT sources
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: APT Update
      apt:
        update_cache: yes

    - name: Check Docker Installation
      shell: apt-cache policy docker-ce
      register: docker_result

    - debug: msg="{{ docker_result.stdout }}"

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Check Docker Installation
      shell: apt-cache policy docker-ce
      register: docker_result

    - debug: msg="{{ docker_result.stdout }}"

    - name: Install pip
      apt:
        name: python-pip
        state: present

    - name: Install VirtualEnv
      apt:
        name: virtualenv
        state: present

    - name: Install Docker-py Python Package
      pip:
        name: docker-py
          
    - name: Pull Hackazon Image
      docker_image:
        name: mutzel/all-in-one-hackazon

    - name: Start HackazonServer1
      docker_container:
        name: Hackazon
        image: mutzel/all-in-one-hackazon
        state: started
        published_ports: 80:80
        restart: yes

    - name: Start HackazonServer2
      docker_container:
        name: Hackazon2
        image: mutzel/all-in-one-hackazon
        state: started
        published_ports: 81:80
        restart: yes

    - name: Start HackazonServer3
      docker_container:
        name: Hackazon3
        image: mutzel/all-in-one-hackazon
        state: started
        published_ports: 82:80
        restart: yes

    - name: Install F5 Module Dependencies
      pip:
        name: f5-sdk bigsuds netaddr objectpath isoparser lxml deepdiff
